language: node_js
node_js:
  - 0.12
env:
  global:
    - GH_REF: vronvali/vronvali.github.io
    - secure: f947112f8e2ddee55be8c0b4c45f4598d1a9f689
before_install:
  - npm install -g bower karma gulp
before_script:
  - export CHROME_BIN=chromium-browser
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
after_success:
  - 'test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy-ghpages.sh'
